package tv.veer.com.news.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import tv.veer.com.news.greenDao.New;

import tv.veer.com.news.greenDao.NewDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newDaoConfig;

    private final NewDao newDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newDaoConfig = daoConfigMap.get(NewDao.class).clone();
        newDaoConfig.initIdentityScope(type);

        newDao = new NewDao(newDaoConfig, this);

        registerDao(New.class, newDao);
    }
    
    public void clear() {
        newDaoConfig.clearIdentityScope();
    }

    public NewDao getNewDao() {
        return newDao;
    }

}
